include: "https://raw.githubusercontent.com/dbmdz/development/master/ci/.gitlab-ci-base.yml"

variables:
  MAVEN_VERIFY_PROFILE: "tests-without-libturbojpeg"

verify:
  extends: .verify
  script: mvn $MAVEN_CLI_OPTS -Dspring.profiles.active=$MAVEN_ACTIVE_PROFILE -P$MAVEN_VERIFY_PROFILE verify

verify:openjdk11:
  extends: .verify
  image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK11"
  script: mvn $MAVEN_CLI_OPTS -Dspring.profiles.active=$MAVEN_ACTIVE_PROFILE -P$MAVEN_VERIFY_PROFILE verify

verify:openjdk11:libturbjpeg:
  extends: .verify
  image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK11_LIBTURBOJPEG"
