# local/default
custom:
  iiif:
    image:
      maxWidth: 65500
      maxHeight: 65500
      canonicalRedirect: true

info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@maven.compiler.source@'
      target: '@maven.compiler.target@'
    project:
      artifactId: '@project.artifactId@'
      buildDetails: '@versionName@'
      groupId: '@project.groupId@'
      name: '@project.name@'
      version: '@project.version@'

management:
  endpoint:
    health:
      show-details: when-authorized
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: '*'
  info:
    git:
      mode: full
  server:
    port: 9001

pathfinder:
  patterns:
    # An image pattern resolving example:
    - pattern: ^img:(\d{8})_(\d{5})$
      templates:
        - '/var/local/iiif/images/%1s/original/image_%1s_%2s.tif'
        - '/var/local/iiif/images/%1s/300/image_%1s_%2s.jpg'
        - '/var/local/iiif/images/%1s/150/image_%1s_%2s.jpg'
    # An manifest pattern resolving example:
    - pattern: ^manifest:(\d{8})$
      template: '/var/local/iiif/presentation/manifests/manifest_%1s.json'
    # Collection manifests ('collection:' pattern-prefix is statically added to requested collection name to disambigued from other patterns)
    - pattern: ^collection:(.*)$
      templates:
        - '/var/local/iiif/presentation/collections/%1s.json'
    # Annotation list of transcriptions
    - pattern: ^transcription:(.*)$
      templates:
        - '/var/local/iiif/presentation/annotations/%1s.json'

server:
  error:
    include-exception: true
    include-stacktrace: always
  port: 9000
  server-header: "@project.name@ v@project.version@"
  tomcat:
    accesslog:
      directory: "/var/log/digitalcollections"
      enabled: true
      prefix: access_log_hymir
      rename-on-rotate: true

spring:
  messages:
    basename: 'messages, messages-commons'
    cache-duration: 5
    encoding: 'UTF-8'
    fallback-to-system-locale: false
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
  thymeleaf:
    cache: false
    mode: HTML

---

# PROD
server:
  error:
    include-exception: false
    include-stacktrace: 'never'

spring:
  profiles: PROD
  thymeleaf:
    cache: true
