# local/default
custom:
  iiif:
    image:
      maxWidth: 65500
      maxHeight: 65500
      canonicalRedirect: true

info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@maven.compiler.source@'
      target: '@maven.compiler.target@'
    project:
      name: '@project.name@'
      groupId: '@project.groupId@'
      artifactId: '@project.artifactId@'
      version: '@project.version@'
      buildDetails: '@versionName@'

management:
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: '*'
  server:
    port: 9001

server:
  port: 9000
  server-header: "@project.name@ v@project.version@"

spring:
  messages:
    basename: messages,messages-overlay,messages-commons
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
      roles: ACTUATOR
  thymeleaf:
    cache: false
    mode: HTML

---

# PROD
spring:
  profiles: PROD
  thymeleaf:
    cache: true